config/routes.rb
Rails.application.routes.draw do
  post 'login', to: 'application#login'
  delete 'logout', to: 'application#logout'
  resources :rooms do
    resources :messages
  end
  root to: 'application#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/lambda_cable/gem_version.rb
module LambdaCable
  def self.gem_version
    Gem::Version.new VERSION::STRING
  end

  module VERSION
    MAJOR = 1
    MINOR = 0
    TINY  = 0
    PRE   = "1"

    STRING = [MAJOR, MINOR, TINY, PRE].compact.join(".")
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :room
  validates :content, presence: true
  scope :recent, -> { order(created_at: :desc).limit(20) }
  
  after_create_commit -> { broadcast_prepend_to room }
  after_update_commit -> { broadcast_replace_to room }
  after_destroy_commit -> { broadcast_remove_to room }
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages
  validates :name, presence: true
  validates :name, uniqueness: true

  scope :recent, -> { order(updated_at: :desc).limit(10) }
end

app/models/user.rb
class User
  include GlobalID::Identification
  attr_reader :name

  def self.find(name)
    new(name)
  end

  def initialize(name)
    @name = name
  end

  def id
    name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :require_current_user
  helper_method :current_user
  
  def index
    redirect_to rooms_url if current_user
  end

  def login
    session[:user_name] = Faker::Name.name
    redirect_to rooms_url
  end

  def logout
    current_connection.disconnect
    session.clear
    redirect_to root_url
  end

  private

  def current_user
    User.find(current_user_name) if current_user_name
  end

  def current_connection
    ActionCable.server.remote_connections.where current_user: current_user
  end

  def current_user_name
    session[:user_name]
  end

  def require_current_user
    return if controller_name == 'application'
    redirect_to root_url unless current_user
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def new
    @message = room.messages.new
  end

  def create
    @message = room.messages.create!(message_params)
    respond_to do |format|
      format.turbo_stream
      format.html { redirect_to room }
    end
  end
  
  private

  def room
    @room ||= Room.find(params[:room_id])
  end

  def message_params
    params.require(:message).permit(:content)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    @rooms = Room.recent
  end

  def show
    room
  end

  def new
    @room = Room.new
  end

  def edit
    room
  end

  def create
    @room = Room.new(room_params)
    if @room.save
      redirect_to room_url(@room), notice: "Room was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if room.update(room_params)
      redirect_to room_url(room), notice: "Room was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    room.destroy
    redirect_to rooms_url, notice: "Room was successfully destroyed."
  end

  private

  def room
    @room ||= Room.find(params[:id])
  end

  def room_params
    params.require(:room).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/application/index.html.erb
<div class="px-4 py-5 my-5 text-center">
  <img class="d-block mx-auto mb-4" src="https://lamby.cloud/img/lamby-logo-small.png" alt="Lamby Logo" height="70">
  <h1 class="display-5 fw-bold text-body-emphasis">
    Rails WebSockets on Lambda
  </h1>
  <div class="col-lg-6 mx-auto">
    <p class="lead mb-4">
      A demonstration of the <a href="https://github.com/rails-lambda/lamby">Lamby</a> & <a href="https://github.com/rails-lambda/lambda_cable">LambdaCable</a> gems. To login and start you unique WebSocket session, click the start button below. You will be assigned a unique session with a random name.
    </p>
    <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
      <%= button_to 'Start Session', login_path, class: 'btn btn-primary btn-lg px-4 gap-3' %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>Rails WebSockets on Lambda</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" crossorigin="anonymous">
    <%= javascript_importmap_tags %>
    <%= action_cable_meta_tag %>
    <%# hotwire_livereload_tags if Rails.env.development? %>
  </head>
  <body>
    <nav class="navbar navbar-expand bg-body-secondary">
      <div class="container-fluid">
        <a class="navbar-brand p-0 m-0" href="/">
          <img src="https://lamby.cloud/img/lamby-logo-small.png" alt="Lamby Logo" height="30" class="d-inline-block align-text-middle m-0 mb-2">
          <span class="fs-6">Rails WebSockets on Lambda</span>
        </a>
        <ul class="navbar-nav">
          <% if current_user %>
            <li class="nav-item">
              <span class="nav-link">👤 <%= current_user.name %></span>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/rooms">🏠 Rooms</a>
            </li>
          <% end %>
          <li class="nav-item">
            <a class="nav-link" href="https://lamby.cloud">📑 Docs</a>
          </li>
          <% if current_user %>
            <li class="nav-item">
              <%= button_to '👋 Logout', logout_path, method: :delete, class: 'nav-link',
                  data: { controller: 'user', action: 'click->user#logout', turbo_method: :delete, turbo_frame: '_top' } %>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>
    <div class="p-3">
      <% if notice %>
        <div id="notice" class="alert alert-info py-2 mb-2" role="alert">
          💁‍♀️ <%= notice %>
        </div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/messages/_message.html.erb
<li id="<%= dom_id(message) %>" class="list-group-item d-flex justify-content-between align-items-start p-0">
  <div class="ms-0 me-3 px-3 py-2">
    <%= message.content %>
  </div>
  <span class="badge bg-dark-subtle rounded-top-0">
    <%= message.created_at.to_fs(:short) %>
  </span>
</li>

app/views/messages/create.turbo_stream.erb
<%= turbo_stream.prepend "messages", @message %>

app/views/messages/new.html.erb
<%= turbo_frame_tag "new_message", target: '_top' do %>
  <%= bootstrap_form_with(model: [@message.room, @message],
      data: {controller: 'send-message', action: 'turbo:submit-end->send-message#reset'}) do |f| %>
    <%= f.text_field :content, hide_label: true, append: f.primary('📨 Send') %>
  <% end %>
<% end %>

app/views/rooms/_form.html.erb
<%= bootstrap_form_with(model: room) do |f| %>
  <%= f.text_field :name %>
  <%= f.primary %>
<% end %>

app/views/rooms/_room.html.erb
<li id="<%= dom_id(room) %>" class="list-group-item d-flex justify-content-between align-items-center">
  <div class="ms-2 me-auto">
    <strong class="fs-4">
      <%= link_to room.name, room %>
    </strong>
  </div>
  <span class="fs-2">💬</span>
</li>

app/views/rooms/edit.html.erb
<%= turbo_frame_tag "room", class: "d-flex flex-row align-items-start " do %>
  <h1 style="padding-right:10px;">Room:</h1>
  <%= bootstrap_form_with(model: @room, class: 'd-box flex-fill mt-1') do |f| %>
    <%= f.text_field :name, wrapper_class: false, hide_label: true, append: [
        link_to("⬅️ Cancel", @room, class: 'btn btn-outline-secondary'),
        f.primary('Rename') ] %>
  <% end %>
<% end %>

app/views/rooms/index.html.erb
<div class="d-flex flex-row align-items-start">
  <h1 class="flex-fill">Rooms</h1>
  <div class="btn-group mt-1" role="group" aria-label="Rooms Actions">
    <%= link_to "🆕 New Room", new_room_path, class: 'btn btn-outline-primary' %>
  </div>
</div>

<ul id="rooms" class="list-group mt-2">
  <% @rooms.each do |room| %>
    <%= render partial: 'room', locals: { room: room } %>
  <% end %>
</ul>

app/views/rooms/new.html.erb
<div class="d-flex flex-row align-items-start">
  <h1 class="flex-fill">New Room</h1>
  <div class="btn-group mt-1" role="group" aria-label="New Room">
    <%= link_to "⬅️ Back", rooms_path, class: 'btn btn-outline-primary' %>
  </div>
</div>

<%= render "form" , room: @room %>

app/views/rooms/show.html.erb
<%= turbo_stream_from(@room) %>

<%= turbo_frame_tag "room", class: "d-flex flex-row align-items-start" do %>
  <h1 class="flex-fill">Room: <%= @room.name %></h1>
  <div class="btn-group mt-1" role="group" aria-label="Room Actions">
    <%= link_to "📝 Edit", edit_room_path(@room), class: 'btn btn-outline-primary' %>
    <%= link_to "🗑️ Destroy", @room, 
      class: 'btn btn-outline-primary', 
      data: { turbo_method: :delete, turbo_confirm: 'Are you sure?', turbo_frame: '_top' } %>
  </div>
<% end %>

<h5 class="text-primary">
  Send Message:
</h5>

<%= turbo_frame_tag "new_message", src: new_room_message_path(@room), target: '_top' %>

<h5 class="text-primary">
  All Messages:
</h5>

<ul id="messages" class="list-group">
  <%= render @room.messages.recent %>
</ul>